package com.getcode.codes.kikcode

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * GATE: the shared code geometry must reproduce the canonical cross-platform fixtures exactly.
 *
 * These run on both Android (host JVM) and iOS (native), so any divergence between the two -- a
 * differing `cos`/`sin` last place, a differing float-to-string -- is caught here rather than as two
 * apps quietly exporting different files.
 *
 * Fixtures anchored to `test-vectors/kikcode.json` and `test-vectors/kikcode_golden.svg`
 * (canonical source), which are generated by an independent Python implementation of the spec.
 */
class KikCodeVectorTest {

    private val document = Json.parseToJsonElement(readTestResource("kikcode.json")).jsonObject

    @Test
    fun geometry_matches_canonical_vectors() {
        val vectors = document["vectors"]!!.jsonArray
        assertTrue(vectors.isNotEmpty(), "no vectors loaded")

        for (element in vectors) {
            val vector = element.jsonObject
            val name = vector["name"]!!.jsonPrimitive.content
            val payload = vector["payload"]!!.jsonPrimitive.content.hexToBytes()
            val dimension = vector["dimension"]!!.jsonPrimitive.content.toDouble()

            val description = KikCodeGeometry.describe(payload, dimension)

            assertEquals(
                vector["center"]!!.jsonPrimitive.content,
                KikCodeSvg.num(description.center),
                "center mismatch for '$name'",
            )
            assertEquals(
                vector["badgeRadius"]!!.jsonPrimitive.content,
                KikCodeSvg.num(description.badgeRadius),
                "badgeRadius mismatch for '$name'",
            )
            assertEquals(
                vector["dotDiameter"]!!.jsonPrimitive.content,
                KikCodeSvg.num(description.dotDiameter),
                "dotDiameter mismatch for '$name'",
            )
            assertEquals(
                vector["marks"]!!.jsonArray.map { it.jsonPrimitive.content },
                description.marks.map { it.encode() },
                "marks mismatch for '$name'",
            )
        }
    }

    @Test
    fun svg_matches_canonical_golden() {
        val golden = document["golden"]!!.jsonObject

        val rendered = KikCodeSvg.render(
            payload = golden["payload"]!!.jsonPrimitive.content.hexToBytes(),
            dimension = golden["dimension"]!!.jsonPrimitive.content.toDouble(),
            foreground = golden["foreground"]!!.jsonPrimitive.content,
            background = golden["background"]!!.jsonPrimitive.content,
        )

        assertEquals(
            readTestResource(golden["file"]!!.jsonPrimitive.content),
            rendered,
            "rendered SVG differs from the canonical golden",
        )
    }
}

/** The fixture's mark encoding: see `test-vectors/gen_kikcode.py`. */
private fun KikCodeMark.encode(): String = when (this) {
    is KikCodeMark.Dot -> "D ${KikCodeSvg.num(x)} ${KikCodeSvg.num(y)}"
    is KikCodeMark.Arc ->
        "A ${KikCodeSvg.num(radius)} ${KikCodeSvg.num(startRadians)} ${KikCodeSvg.num(sweepRadians)}"
    is KikCodeMark.Ring -> "R ${KikCodeSvg.num(radius)}"
}

private fun String.hexToBytes(): ByteArray =
    if (isEmpty()) ByteArray(0)
    else ByteArray(length / 2) { i ->
        ((this[i * 2].digitToInt(16) shl 4) or this[i * 2 + 1].digitToInt(16)).toByte()
    }
