version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  labels:
    - "dependencies"
    - "type: build"
  target-branch: code/cash
  reviewers:
  - bmc08gt
  assignees:
  - bmc08gt
