publisher:
  name: Flipcash
  website: https://flipcash.com
  email: support@flipcash.com
  address: null
  media:
    - purpose: icon
      uri: ../../../../fastlane/metadata/flipcash/en-US/images/icon.png
    - purpose: banner
      uri: ../../../../fastlane/metadata/flipcash/en-US/dappStore/banner.jpeg
    - purpose: featureGraphic
      uri: .../../../../fastlane/metadata/flipcash/en-US/dappStore/featureGraphic.png
app:
  name: Flipcash
  address: BiJpNgpFRtxWfgSgypWp7q8VddRgmAHpKPU5KtM8CXvr
  android_package: com.flipcash.android.app
  urls:
    license_url: https://www.flipcash.com/terms
    copyright_url: https://www.flipcash.com/terms
    privacy_policy_url: https://www.flipcash.com/privacy
    website: https://flipcash.com
  media:
    - purpose: icon
      uri: ../../../../fastlane/metadata/flipcash/en-US/images/icon.png
release:
  address: BNqxUwVyp2Nu9UKrNH2WNKpZmj1Uv5L95haWuEHg9hqS
  media:
    - purpose: icon
      uri: ../../../../fastlane/metadata/flipcash/en-US/images/icon.png
    - purpose: banner
      uri: ../../../../fastlane/metadata/flipcash/en-US/dappStore/banner.jpeg
    - purpose: featureGraphic
      uri: ../../../../fastlane/metadata/flipcash/en-US/dappStore/featureGraphic.png
    - purpose: screenshot
      uri: ../../../../fastlane/metadata/flipcash/en-US/images/phoneScreenshots/1_en-US.jpeg
    - purpose: screenshot
      uri: ../../../../fastlane/metadata/flipcash/en-US/images/phoneScreenshots/2_en-US.jpeg
    - purpose: screenshot
      uri: ../../../../fastlane/metadata/flipcash/en-US/images/phoneScreenshots/3_en-US.jpeg
    - purpose: screenshot
      uri: ../../../../fastlane/metadata/flipcash/en-US/images/phoneScreenshots/4_en-US.jpeg
    - purpose: screenshot
      uri: ../../../../fastlane/metadata/flipcash/en-US/images/phoneScreenshots/5_en-US.jpeg
    - purpose: screenshot
      uri: ../../../../fastlane/metadata/flipcash/en-US/images/phoneScreenshots/6_en-US.jpeg
    - purpose: video
      uri: ../../../../fastlane/metadata/flipcash/en-US/dappStore/flipcash_promo.mp4
  files:
    - purpose: install
      uri: <<<UPDATE THIS FIELD>>>
  catalog:
    en-US:
      name: Flipcash
      short_description: This is Digital Cash
      long_description: |-
        You can hand it to someone. 

        Or send it around the world. 

        Pick any currency in any country.

        It's always instant, and always free. Just like cash.
      new_in_version: Initial Release of Flipcash on Solana Mobile
      saga_features: None
solana_mobile_dapp_publisher_portal:
  google_store_package: com.flipcash.android.app
  testing_instructions: |-
    <<<UPDATE THIS FIELD>>>
lastSubmittedVersionOnChain:
  address: BNqxUwVyp2Nu9UKrNH2WNKpZmj1Uv5L95haWuEHg9hqS
  version_code: 2625
  apk_hash: DILL5WhA1GvWpYNMrmLWYcPJ7fvPfUmrHxu62YyaCNs=
lastUpdatedVersionOnStore:
  address: BNqxUwVyp2Nu9UKrNH2WNKpZmj1Uv5L95haWuEHg9hqS
