syntax = "proto3";
package flipcash.pool.v1;
option go_package = "github.com/code-payments/flipcash-protobuf-api/generated/go/pool/v1;poolpb";
option java_package = "com.codeinc.flipcash.gen.pool.v1";
option objc_class_prefix = "FPBPoolV1";
import "pool/v1/model.proto";
import "common/v1/common.proto";

service Pool {
    // CreatePool creates a new pool
    rpc CreatePool(CreatePoolRequest) returns (CreatePoolResponse);
    // GetPool gets pool metadata by its ID
    rpc GetPool(GetPoolRequest) returns (GetPoolResponse);
    // DeclarePoolOutcome declares a pool's outcome. The pool creator resolves a
    // pool by calling this RPC first, then SubmitIntent to distribute pool funds
    // to the winning participants.
    rpc DeclarePoolOutcome(DeclarePoolOutcomeRequest) returns (DeclarePoolOutcomeResponse);
    // MakeBet creates a new bet against a pool. Pool participants make a bet by
    // calling MakeBet to create an initially unpaid bet, then SubmitIntent for
    // payment where:
    //  1. Intent ID == Bet.id
    //  2. Payment amount == PoolMetadata.buy_in
    //  3. Payment destination == PoolMetadata.funding_destination
    // Bets without payment, or with invalid intents, will not be visible in the
    // PoolMetadata when calling GetPool.
    rpc MakeBet(MakeBetRequest) returns (MakeBetResponse);
}
message CreatePoolRequest {
    SignedPoolMetadata pool = 1;
    common.v1.Signature rendezvous_signature = 2;
    common.v1.Auth auth = 3;
}
message CreatePoolResponse {
    Result result = 1;
    enum Result {
        OK                         = 0;
        RENDEZVOUS_EXISTS          = 1;
        FUNDING_DESTINATION_EXISTS = 2;
    }
}
message GetPoolRequest {
    PoolId id = 1;
}
message GetPoolResponse {
    Result result = 1;
    enum Result {
        OK        = 0;
        NOT_FOUND = 1;
    }
    PoolMetadata pool = 2;
}
message DeclarePoolOutcomeRequest {
    PoolId id = 1;
    
    Resolution resolution = 2;
    common.v1.Signature new_rendezvous_signature = 3;
    common.v1.Auth auth = 4;
}
message DeclarePoolOutcomeResponse {
    Result result = 1;
    enum Result {
        OK                         = 0;
        DENIED                     = 1;
        NOT_FOUND                  = 2;
        DIFFERENT_OUTCOME_DECLARED = 3;
    }
}
message MakeBetRequest {
    PoolId pool_id = 1;
    SignedBetMetadata bet = 2;
    common.v1.Signature rendezvous_signature = 3;
    common.v1.Auth auth = 4;
}
message MakeBetResponse {
    Result result = 1;
    enum Result {
        OK               = 0;
        POOL_NOT_FOUND   = 1;
        POOL_CLOSED      = 2;
        MULTIPLE_BETS    = 3;
    }
}
