package com.getcode.opencode.model.messaging

import com.getcode.ed25519.Ed25519.KeyPair
import com.getcode.model.Domain
import com.getcode.opencode.model.core.ID
import com.getcode.opencode.model.transactions.AirdropType
import com.getcode.opencode.model.transactions.ExchangeData
import com.getcode.opencode.model.transactions.TransactionMetadata
import com.getcode.solana.keys.PublicKey
import com.getcode.solana.keys.Signature

/**
 * @param id the unique identifier of the message, generated by the server and always set when
 *           receiving a message. The server generates this ID to:
 *           <ol>
 *             <li>Reserve the ability to modify ID generation in the future</li>
 *             <li>Prevent clients from attempting to create conflicting message IDs</li>
 *           </ol>
 * @param signature the signature included in a SendMessageRequest, injected by the server to
 *           allow clients to verify that no Man-in-the-Middle (MITM) attacks have
 *           altered the contents of the typed message. This signature is only
 *           applicable to messages not generated by the server.
 *  @param kind The [MessageKind]
 */
data class Message(
    val id: ID,
    val signature: Signature,
    val kind: MessageKind
)

sealed interface MessageKind {

    // region Cash
    /**
     * Represents a request that a pulled out bill be sent to the requested address.
     * <p>
     * This message type can only be initiated by clients.
     *
     * @param requestor is the virtual token account on the VM to which a payment
     */
    data class RequestToGrabBill(
        val requestor: PublicKey
    ): MessageKind

    /**
     * Represents a request that a bill be given in the desired mint
     * <p>
     * This message type can only be initiated by clients.
     *
     * @param mint is the mint that the bill will be received in
     */
    data class RequestToGiveBill(
        val mint: PublicKey
    ): MessageKind
    // endregion

    data object Unknown: MessageKind
}