syntax = "proto3";
package code.currency.v1;
option go_package = "github.com/code-payments/code-protobuf-api/generated/go/currency/v1;currency";
option java_package = "com.codeinc.opencode.gen.currency.v1";
option objc_class_prefix = "CPBCurrencyV1";
import "common/v1/model.proto";

import "google/protobuf/timestamp.proto";
service Currency {
    // GetAllRates returns the exchange rates for the core mint token against all
    // available currencies
    rpc GetAllRates(GetAllRatesRequest) returns (GetAllRatesResponse);
    // GetMints gets mint account metadata by address
    rpc GetMints(GetMintsRequest) returns (GetMintsResponse);
}
message GetAllRatesRequest {
    // If timestamp is included, the returned rate will be the most recent available
    // exchange rate prior to the provided timestamp within the same day. Otherwise,
    // the latest rates will be returned.
    google.protobuf.Timestamp timestamp = 1;
}
message GetAllRatesResponse {
    Result result = 1;
    enum Result {
        OK = 0;
        // No currency data is available for the requested timestamp.
        MISSING_DATA = 1;
    }
    // The time the exchange rates were observed
    google.protobuf.Timestamp as_of = 2;
    // The price of 1 core mint token in different currencies, keyed on 3- or 4-
    // letter lowercase currency code.
    map<string, double> rates = 3 ;
}
message GetMintsRequest {
    repeated common.v1.SolanaAccountId addresses = 1 ;
}
message GetMintsResponse {
    Result result = 1;
    enum Result {
        OK        = 0;
        NOT_FOUND = 1;
    }
    map<string, Mint> metadata_by_address = 2;
}
message Mint {
    // Token mint address
    common.v1.SolanaAccountId address = 1;
    // The number of decimals configured for the mint
    uint32 decimals = 2;
    // Currency name
    string name = 3 ;
    // Currency ticker symbol
    string symbol = 4 ;
    // Currency description
    string description = 5 ;
    // URL to currency image
    string image_url = 6 ;
    // Available when a VM exists for the given mint, and can be used for deriving
    // VM deposit PDAs
    //
    // Note: Only currencies with a VM are useable for payments
    VmMetadata vm_metadata = 7;
    // Available when created by the launchpad via the currency creator program, and
    // can be used for calculating price, market cap, etc. based on the exponential
    // bonding curve
    LaunchpadMetadata launchpad_metadata = 8;
}
message VmMetadata {
    // VM address
    common.v1.SolanaAccountId vm = 1;
    // Authority that subsidizes and authorizes all transactions against the VM
    common.v1.SolanaAccountId authority = 2;
    // Lock duration of Virtual Timelock Accounts on the VM, currently hardcoded
    // to 21 days
    uint32 lock_duration_in_days = 3;
}
message LaunchpadMetadata {
    // The address of the currency config
    common.v1.SolanaAccountId currency_config = 1;
    // The address of the liquidity pool
    common.v1.SolanaAccountId liquidity_pool = 2;
    // The random seed used during currency creation
    common.v1.SolanaAccountId seed = 3;
    // The address of the authority for the currency
    common.v1.SolanaAccountId authority = 4;
    // The address where this mint's tokens are locked against the liquidity pool
    common.v1.SolanaAccountId mint_vault = 5;
    // The address where core mint tokens are locked against the liquidity pool
    common.v1.SolanaAccountId core_mint_vault = 6;
    // Reserved for mint_fees if we enable buy fees
    reserved 7;
    // The address where core mint fees are paid
    common.v1.SolanaAccountId core_mint_fees = 8;
    // Current circulating mint token supply in quarks
    uint64 supply_from_bonding = 9;
    // Current core mint quarks locked in the liquidity pool
    uint64 core_mint_locked = 10;
    // Reserved for buy_fee_bps if we enable buy fees
    reserved 11;
    // Precent fee for sells in basis points, currently hardcoded to 1%
    uint32 sell_fee_bps = 12;
}
