// Generated by code/test-vectors/gen_text_format_unicode.py. Do not edit.
// Unicode 16.0.0. Regenerate with:
//   python3 gen_text_format_unicode.py test > TextFormatUnicodeTest.kt
package com.flipcash.libs.textformat

import kotlin.test.Test
import kotlin.test.assertEquals

class TextFormatUnicodeTest {
    @Test
    fun version() {
        assertEquals("16.0.0", TextFormatUnicode.UNICODE_VERSION)
    }

    @Test
    fun probes() {
        assertEquals(CodePointClass.LETTER, TextFormatUnicode.classify(0x41)) // A
        assertEquals(CodePointClass.LETTER, TextFormatUnicode.classify(0xE9)) // e acute, precomposed
        assertEquals(CodePointClass.MARK, TextFormatUnicode.classify(0x301)) // combining acute
        assertEquals(CodePointClass.MARK, TextFormatUnicode.classify(0xFE0F)) // variation selector 16, after emoji
        assertEquals(CodePointClass.DIGIT, TextFormatUnicode.classify(0x30)) // 0
        assertEquals(CodePointClass.DIGIT, TextFormatUnicode.classify(0x663)) // Arabic-Indic three
        assertEquals(CodePointClass.OTHER, TextFormatUnicode.classify(0xB2)) // superscript two is No, not Nd
        assertEquals(CodePointClass.LETTER, TextFormatUnicode.classify(0x5B57)) // Han character
        assertEquals(CodePointClass.LETTER, TextFormatUnicode.classify(0x1D400)) // mathematical bold A, outside the BMP
        assertEquals(CodePointClass.PUNCT, TextFormatUnicode.classify(0x1F600)) // grinning face is So
        assertEquals(CodePointClass.PUNCT, TextFormatUnicode.classify(0x2A)) // asterisk
        assertEquals(CodePointClass.PUNCT, TextFormatUnicode.classify(0x5F)) // low line
        assertEquals(CodePointClass.PUNCT, TextFormatUnicode.classify(0x24)) // dollar sign is Sc
        assertEquals(CodePointClass.PUNCT, TextFormatUnicode.classify(0xB4)) // acute accent is Sk
        assertEquals(CodePointClass.SPACE, TextFormatUnicode.classify(0x20)) // space
        assertEquals(CodePointClass.SPACE, TextFormatUnicode.classify(0xA0)) // no-break space
        assertEquals(CodePointClass.SPACE, TextFormatUnicode.classify(0x3000)) // ideographic space
        assertEquals(CodePointClass.OTHER, TextFormatUnicode.classify(0x9)) // tab is Cc; the parser handles it
        assertEquals(CodePointClass.OTHER, TextFormatUnicode.classify(0x200B)) // zero width space is Cf
        assertEquals(CodePointClass.OTHER, TextFormatUnicode.classify(0x200D)) // zero width joiner is Cf
        assertEquals(CodePointClass.OTHER, TextFormatUnicode.classify(0xD800)) // lone surrogate
        assertEquals(CodePointClass.OTHER, TextFormatUnicode.classify(0x10FFFF)) // last code point
    }

    // Per-class totals over every code point catch a corrupted or truncated table.
    @Test
    fun classTotals() {
        val counts = IntArray(6)
        for (cp in 0..0x10FFFF) counts[TextFormatUnicode.classify(cp).ordinal]++
        assertEquals(960437, counts[CodePointClass.OTHER.ordinal])
        assertEquals(141028, counts[CodePointClass.LETTER.ordinal])
        assertEquals(2501, counts[CodePointClass.MARK.ordinal])
        assertEquals(760, counts[CodePointClass.DIGIT.ordinal])
        assertEquals(9369, counts[CodePointClass.PUNCT.ordinal])
        assertEquals(17, counts[CodePointClass.SPACE.ordinal])
    }
}
