#!/usr/bin/env python3
"""
Generates `kikcode.json` (+ `kikcode_golden.svg`), the parity gate for the Kik code graphic.

Written as an *independent* implementation of the drawing spec -- from the ratios, not from the
Kotlin -- so a transcription slip in `:libs:codes:kikcode` shows up as a failing vector rather than
matching fixtures generated by the same mistake.

Marks are encoded as compact strings so comparison is exact rather than float-fuzzy:

    "D <x> <y>"                  a lone dot
    "A <radius> <start> <sweep>" a run of consecutive set bits, angles in radians
    "R <radius>"                 a ring whose every bit is set

Every number uses the same 3-decimal, ties-toward-positive-infinity rounding the Kotlin writer
applies, which is what makes the emitted SVG byte-identical on JVM and Native.

Usage:  python3 gen_kikcode.py
"""

import hashlib
import json
import math
import os

RING_COUNT = 6
BASE_BITS_PER_RING = 32
BITS_PER_RING_STEP = 8

INNER_RING_RATIO = 0.32
FIRST_RING_RATIO = 0.425
LAST_RING_RATIO = 0.95
DOT_RATIO = 0.75
OUTER_RATIO = 0.5

FINDER_BYTES = bytes([0xB2, 0xCB, 0x25, 0xC6])
MAX_PAYLOAD_BYTES = 35

BADGE_VIEWPORT = 62.0
BADGE_PATH = None  # filled in from the Kotlin constant at run time


def num(value):
    """3-decimal rounding, ties toward positive infinity (Kotlin `roundToLong`)."""
    scaled = math.floor(value * 1000.0 + 0.5)
    if scaled == 0:
        return "0"
    negative = scaled < 0
    magnitude = -scaled if negative else scaled
    fraction = str(magnitude % 1000).rjust(3, "0").rstrip("0")
    out = ("-" if negative else "") + str(magnitude // 1000)
    if fraction:
        out += "." + fraction
    return out


def bit_at(data, offset):
    index = offset // 8
    if index >= len(data):
        return False
    return (data[index] & (1 << (offset % 8))) != 0


def ring_marks(bits, radius, center):
    n = len(bits)
    delta = 2.0 * math.pi / n
    if all(bits):
        return [("R", radius, None, None)]
    if not any(bits):
        return []

    marks = []
    for index in range(n):
        if not bits[index]:
            continue
        if bits[(index - 1 + n) % n]:  # not a run head
            continue
        length = 1
        while bits[(index + length) % n]:
            length += 1
        angle = index * delta - math.pi / 2.0
        if length == 1:
            marks.append(
                ("D", center + radius * math.cos(angle), center + radius * math.sin(angle), None)
            )
        else:
            marks.append(("A", radius, angle, delta * (length - 1)))
    return marks


def describe(payload, dimension):
    data = FINDER_BYTES + payload
    center = dimension / 2.0
    outer_radius = dimension * OUTER_RATIO
    badge_radius = outer_radius * INNER_RING_RATIO
    first_edge = outer_radius * FIRST_RING_RATIO
    last_edge = outer_radius * LAST_RING_RATIO
    ring_width = (last_edge - first_edge) / RING_COUNT

    marks = []
    offset = 0
    for ring in range(RING_COUNT):
        inner_edge = ring_width * ring + first_edge
        if ring == 0:
            inner_edge -= badge_radius / 10.0
        bit_count = BASE_BITS_PER_RING + BITS_PER_RING_STEP * ring
        bits = [bit_at(data, offset + j) for j in range(bit_count)]
        marks += ring_marks(bits, inner_edge + ring_width / 2.0, center)
        offset += bit_count

    return {
        "dimension": dimension,
        "center": center,
        "badgeRadius": badge_radius,
        "dotDiameter": ring_width * DOT_RATIO,
        "marks": marks,
    }


def encode_mark(mark):
    kind, a, b, c = mark
    if kind == "D":
        return "D %s %s" % (num(a), num(b))
    if kind == "R":
        return "R %s" % num(a)
    return "A %s %s %s" % (num(a), num(b), num(c))


def render_svg(description, foreground="#FFFFFF", background=None, include_badge=True):
    side = num(description["dimension"])
    center = description["center"]
    dot_diameter = description["dotDiameter"]
    out = []
    out.append(
        '<svg xmlns="http://www.w3.org/2000/svg" width="%s" height="%s" viewBox="0 0 %s %s">\n'
        % (side, side, side, side)
    )
    if background is not None:
        out.append('<rect width="%s" height="%s" fill="%s"/>\n' % (side, side, background))

    dots = [m for m in description["marks"] if m[0] == "D"]
    if dots:
        radius = num(dot_diameter / 2.0)
        out.append('<g fill="%s">\n' % foreground)
        for _, x, y, _unused in dots:
            out.append('<circle cx="%s" cy="%s" r="%s"/>\n' % (num(x), num(y), radius))
        out.append("</g>\n")

    strokes = [m for m in description["marks"] if m[0] != "D"]
    if strokes:
        out.append(
            '<g fill="none" stroke="%s" stroke-width="%s" stroke-linecap="round">\n'
            % (foreground, num(dot_diameter))
        )
        for kind, radius, start, sweep in strokes:
            if kind == "R":
                out.append(
                    '<circle cx="%s" cy="%s" r="%s"/>\n' % (num(center), num(center), num(radius))
                )
            else:
                end = start + sweep
                large_arc = 1 if sweep > math.pi else 0
                out.append(
                    '<path d="M %s %s A %s %s 0 %d 1 %s %s"/>\n'
                    % (
                        num(center + radius * math.cos(start)),
                        num(center + radius * math.sin(start)),
                        num(radius),
                        num(radius),
                        large_arc,
                        num(center + radius * math.cos(end)),
                        num(center + radius * math.sin(end)),
                    )
                )
        out.append("</g>\n")

    if include_badge:
        diameter = description["badgeRadius"] * 2.0
        origin = center - description["badgeRadius"]
        out.append(
            '<g fill="%s" fill-rule="evenodd" transform="translate(%s %s) scale(%s)">\n'
            % (foreground, num(origin), num(origin), num(diameter / BADGE_VIEWPORT))
        )
        out.append('<path d="%s"/>\n' % BADGE_PATH)
        out.append("</g>\n")

    out.append("</svg>\n")
    return "".join(out)


def load_badge_path():
    """Reads the badge path from the shared Kotlin constant (it is one long literal)."""
    here = os.path.dirname(os.path.abspath(__file__))
    src = os.path.join(
        here, "..", "libs", "codes", "kikcode", "src", "commonMain", "kotlin",
        "com", "getcode", "codes", "kikcode", "KikCodeBadge.kt",
    )
    with open(src) as handle:
        for line in handle:
            stripped = line.strip()
            if stripped.startswith('"M') and stripped.endswith('"'):
                return stripped[1:-1]
    raise SystemExit("badge path not found in KikCodeBadge.kt")


def digest_bytes(seed, length):
    """Deterministic pseudo-random payload, so vectors are reproducible without a fixed blob."""
    out = b""
    counter = 0
    while len(out) < length:
        out += hashlib.sha256(("%s:%d" % (seed, counter)).encode()).digest()
        counter += 1
    return out[:length]


CASES = [
    # name, payload, dimension
    ("zeros-20", bytes(20), 1024.0),
    ("ones-20", bytes([0xFF] * 20), 1024.0),
    ("alternating-20", bytes([0xAA] * 20), 1024.0),
    ("tip-card-20", digest_bytes("flipcash tip card", 20), 1024.0),
    ("tip-card-20-at-300", digest_bytes("flipcash tip card", 20), 300.0),
    ("tip-card-20-at-512", digest_bytes("flipcash tip card", 20), 512.0),
    ("single-byte", bytes([0x01]), 1024.0),
    ("max-payload-35", digest_bytes("max payload", MAX_PAYLOAD_BYTES), 1024.0),
]

GOLDEN_CASE = ("tip-card-20", digest_bytes("flipcash tip card", 20), 512.0)
GOLDEN_FOREGROUND = "#FFFFFF"
GOLDEN_BACKGROUND = "#000000"


def main():
    global BADGE_PATH
    BADGE_PATH = load_badge_path()
    here = os.path.dirname(os.path.abspath(__file__))

    vectors = []
    for name, payload, dimension in CASES:
        description = describe(payload, dimension)
        vectors.append({
            "name": name,
            "payload": payload.hex(),
            "dimension": num(dimension),
            "center": num(description["center"]),
            "badgeRadius": num(description["badgeRadius"]),
            "dotDiameter": num(description["dotDiameter"]),
            "marks": [encode_mark(m) for m in description["marks"]],
        })

    _, golden_payload, golden_dimension = GOLDEN_CASE
    golden = render_svg(
        describe(golden_payload, golden_dimension),
        foreground=GOLDEN_FOREGROUND,
        background=GOLDEN_BACKGROUND,
    )

    document = {
        "description": (
            "Kik code graphic geometry. Marks are 'D x y' (dot), "
            "'A radius start sweep' (arc, radians) or 'R radius' (full ring); "
            "numbers are rounded to 3 decimals, ties toward positive infinity."
        ),
        "golden": {
            "case": GOLDEN_CASE[0],
            "payload": golden_payload.hex(),
            "dimension": num(golden_dimension),
            "foreground": GOLDEN_FOREGROUND,
            "background": GOLDEN_BACKGROUND,
            "file": "kikcode_golden.svg",
            "sha256": hashlib.sha256(golden.encode()).hexdigest(),
        },
        "vectors": vectors,
    }

    with open(os.path.join(here, "kikcode.json"), "w") as handle:
        json.dump(document, handle, indent=2)
        handle.write("\n")
    with open(os.path.join(here, "kikcode_golden.svg"), "w") as handle:
        handle.write(golden)

    total = sum(len(v["marks"]) for v in vectors)
    print("wrote kikcode.json (%d vectors, %d marks)" % (len(vectors), total))
    print("wrote kikcode_golden.svg (%d bytes)" % len(golden))


if __name__ == "__main__":
    main()
