package com.flipcash.services.internal.model.billing

/**
 * Additional IAP metadata, which can be trusted given a verified receipt (they can
 * only be generated by production-signed apps).
 */
data class IapMetadata(
    val product: String,
    val currency: String,
    val amount: Double,
)
